import {
  Box,
  Container,
  FormHelperText,
  Grid,
  Heading,
  HStack,
  SimpleGrid,
  Stack,
  Tab,
  Table,
  TableContainer,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Tbody,
  Td,
  Text,
  Tfoot,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import { Form } from "../src/components/forms";

export default function Home() {
  let [data, setData] = React.useState([]);
  let [form, setForm] = React.useState({});

  let handleChange = (e) => {
    const name = e.target.name;
    const value = e.target.value;
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  let handleSubmit = (e) => {
    e.preventDefault();
    setForm({});
    setData((prev) => [...prev, form]);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as={"main"} py={6}>
        <Container maxW={"container.xl"}>
          <Stack spacing={6}>
            <SimpleGrid columns={3} spacing={6}>
              <Stack p={6} shadow={"base"} rounded="2xl">
                <Heading textAlign={"center"} size={"sm"}>
                  Whatsapp
                </Heading>
                <Text textAlign={"center"}>1</Text>
              </Stack>
              <Stack p={6} shadow={"base"} rounded="2xl">
                <Heading textAlign={"center"} size={"sm"}>
                  Call
                </Heading>
                <Text textAlign={"center"}>1</Text>
              </Stack>
              <Stack p={6} shadow={"base"} rounded="2xl">
                <Heading textAlign={"center"} size={"sm"}>
                  Email
                </Heading>
                <Text textAlign={"center"}>1</Text>
              </Stack>
            </SimpleGrid>
            <Box>
              <Form handleChange={handleChange} handleSubmit={handleSubmit} />
            </Box>
            <TableContainer py={6} shadow={"base"} rounded={"2xl"}>
              <Table variant="simple">
                <Thead>
                  <Tr>
                    <Th>Nama</Th>
                    <Th>Sumber Pesanan</Th>
                    <Th>Email</Th>
                    <Th isNumeric>HP</Th>
                    <Th isNumeric>Jumlah Roti</Th>
                    <Th>Keterangan</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  <Tr>
                    <Td>Joko</Td>
                    <Td>Whatsapp</Td>
                    <Td>joko@joko.com</Td>
                    <Td isNumeric>08572723273</Td>
                    <Td isNumeric>5</Td>
                    <Td>Coklat Semua</Td>
                  </Tr>
                  {data &&
                    data.map((item) => (
                      <Tr key={item}>
                        <Td>{item.name}</Td>
                        <Td>{item.order}</Td>
                        <Td>{item.email}</Td>
                        <Td isNumeric>{item.phone}</Td>
                        <Td isNumeric>{item.total}</Td>
                        <Td>{item.description}</Td>
                      </Tr>
                    ))}
                </Tbody>
              </Table>
            </TableContainer>
          </Stack>
        </Container>
      </Box>

      <footer></footer>
    </div>
  );
}
